// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type ActivityEntry struct {
	ActivityId  int             `json:"activity_id"`
	App         string          `json:"app"`
	Datetime    string          `json:"datetime"`
	Icon        string          `json:"icon"`
	Link        string          `json:"link"`
	Message     string          `json:"message"`
	ObjectId    int             `json:"object_id"`
	ObjectName  string          `json:"object_name"`
	ObjectType  string          `json:"object_type"`
	Objects     json.RawMessage `json:"objects"`
	Subject     string          `json:"subject"`
	SubjectRich string          `json:"subject_rich"`
	Type        string          `json:"type"`
	User        string          `json:"user"`
}

type Capabilities struct {
	Capabilities json.RawMessage `json:"capabilities"`
	Version      json.RawMessage `json:"version"`
}

type DeckBoard struct {
	Archived     bool            `json:"archived"`
	Color        string          `json:"color"`
	DeletedAt    int             `json:"deletedAt"`
	Id           int             `json:"id"`
	LastModified int             `json:"lastModified"`
	Owner        json.RawMessage `json:"owner"`
	Shared       int             `json:"shared"`
	Title        string          `json:"title"`
}

type DeckCard struct {
	Archived     bool            `json:"archived"`
	CreatedAt    int             `json:"createdAt"`
	DeletedAt    int             `json:"deletedAt"`
	Description  string          `json:"description"`
	Duedate      string          `json:"duedate"`
	Id           int             `json:"id"`
	LastEditor   string          `json:"lastEditor"`
	LastModified int             `json:"lastModified"`
	Owner        json.RawMessage `json:"owner"`
	StackId      int             `json:"stackId"`
	Title        string          `json:"title"`
	Type         string          `json:"type"`
}

type DeckStack struct {
	BoardId   int             `json:"boardId"`
	Cards     json.RawMessage `json:"cards"`
	DeletedAt int             `json:"deletedAt"`
	Id        int             `json:"id"`
	Order     int             `json:"order"`
	Title     string          `json:"title"`
}

type FileEntry struct {
	Contenttype  string `json:"contenttype"`
	Etag         string `json:"etag"`
	Href         string `json:"href"`
	Lastmodified string `json:"lastmodified"`
	Name         string `json:"name"`
	Size         int    `json:"size"`
	Type         string `json:"type"`
}

type NoteEntry struct {
	Category  string `json:"category"`
	Content   string `json:"content"`
	Error     bool   `json:"error"`
	ErrorType string `json:"errorType"`
	Etag      string `json:"etag"`
	Favorite  bool   `json:"favorite"`
	Id        int    `json:"id"`
	Modified  int    `json:"modified"`
	Readonly  bool   `json:"readonly"`
	Title     string `json:"title"`
}

type OCSEnvelope struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OCSMeta struct {
	Message    string `json:"message"`
	Status     string `json:"status"`
	Statuscode int    `json:"statuscode"`
}

type OcsAddUserToGroupResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsClearUserStatusMessageResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsCreateGroupResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsCreateShareResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsCreateUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsDeleteGroupResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsDeleteShareResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsDeleteUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsDisableUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsEnableUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetCapabilitiesResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetGroupMembersResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetShareResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetUserGroupsResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsGetUserStatusResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListActivityResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListGroupsResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListNotificationsResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListRoomsResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListSharesResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListUserStatusesResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsListUsersResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsReadMessagesResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsRemoveUserFromGroupResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsSendMessageResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsSendNotificationResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsSetUserStatusMessageResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsUpdateShareResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type OcsUpdateUserResponse struct {
	Ocs json.RawMessage `json:"ocs"`
}

type ShareEntry struct {
	DisplaynameFileOwner string `json:"displayname_file_owner"`
	DisplaynameOwner     string `json:"displayname_owner"`
	Expiration           string `json:"expiration"`
	HideDownload         int    `json:"hide_download"`
	Id                   string `json:"id"`
	ItemSource           int    `json:"item_source"`
	ItemType             string `json:"item_type"`
	MailSend             int    `json:"mail_send"`
	Parent               string `json:"parent"`
	Path                 string `json:"path"`
	Permissions          int    `json:"permissions"`
	ShareType            int    `json:"share_type"`
	ShareWith            string `json:"share_with"`
	ShareWithDisplayname string `json:"share_with_displayname"`
	Stime                int    `json:"stime"`
	Token                string `json:"token"`
	UidFileOwner         string `json:"uid_file_owner"`
	UidOwner             string `json:"uid_owner"`
	Url                  string `json:"url"`
}

type SystemTag struct {
	CanAssign      bool   `json:"canAssign"`
	Id             int    `json:"id"`
	Name           string `json:"name"`
	UserAssignable bool   `json:"userAssignable"`
	UserVisible    bool   `json:"userVisible"`
}

type TalkMessage struct {
	ActorDisplayName  string          `json:"actorDisplayName"`
	ActorId           string          `json:"actorId"`
	ActorType         string          `json:"actorType"`
	Id                int             `json:"id"`
	Message           string          `json:"message"`
	MessageParameters json.RawMessage `json:"messageParameters"`
	MessageType       string          `json:"messageType"`
	SystemMessage     string          `json:"systemMessage"`
	Timestamp         int             `json:"timestamp"`
	Token             string          `json:"token"`
}

type TalkRoom struct {
	DisplayName     string `json:"displayName"`
	HasCall         bool   `json:"hasCall"`
	HasPassword     bool   `json:"hasPassword"`
	LastActivity    int    `json:"lastActivity"`
	Name            string `json:"name"`
	ParticipantType int    `json:"participantType"`
	Token           string `json:"token"`
	Type            int    `json:"type"`
	UnreadMention   bool   `json:"unreadMention"`
	UnreadMessages  int    `json:"unreadMessages"`
}

type UserEntry struct {
	Backend         string          `json:"backend"`
	Displayname     string          `json:"displayname"`
	Email           string          `json:"email"`
	Enabled         bool            `json:"enabled"`
	Groups          json.RawMessage `json:"groups"`
	Id              string          `json:"id"`
	Language        string          `json:"language"`
	LastLogin       int             `json:"last_login"`
	Locale          string          `json:"locale"`
	Quota           json.RawMessage `json:"quota"`
	StorageLocation string          `json:"storageLocation"`
	Subadmin        json.RawMessage `json:"subadmin"`
}
