// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"nextcloud-pp-cli/internal/cli"
	"nextcloud-pp-cli/internal/client"
	"nextcloud-pp-cli/internal/cliutil"
	"nextcloud-pp-cli/internal/config"
	"nextcloud-pp-cli/internal/mcp/cobratree"
	"nextcloud-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("index-php_create-deck-board",
			mcplib.WithDescription("Create a Deck board. Required: color, title. Returns the new DeckBoard."),
			mcplib.WithString("color", mcplib.Required(), mcplib.Description("Hex color without # (e.g. ff0000)")),
			mcplib.WithString("title", mcplib.Required(), mcplib.Description("Title")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/index.php/apps/deck/api/v1.0/boards", false, []mcpParamBinding{{PublicName: "color", WireName: "color", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_create-deck-card",
			mcplib.WithDescription("Create a card in a Deck stack. Required: boardId, stackId, title. Optional: description, duedate, order. Returns the new DeckCard."),
			mcplib.WithNumber("boardId", mcplib.Required(), mcplib.Description("Board id")),
			mcplib.WithNumber("stackId", mcplib.Required(), mcplib.Description("Stack id")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("duedate", mcplib.Description("Duedate")),
			mcplib.WithNumber("order", mcplib.Description("Order")),
			mcplib.WithString("title", mcplib.Required(), mcplib.Description("Title")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/index.php/apps/deck/api/v1.0/boards/{boardId}/stacks/{stackId}/cards", false, []mcpParamBinding{{PublicName: "boardId", WireName: "boardId", Location: "path"}, {PublicName: "stackId", WireName: "stackId", Location: "path"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "duedate", WireName: "duedate", Location: "body"}, {PublicName: "order", WireName: "order", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"boardId", "stackId"}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_create-note",
			mcplib.WithDescription("Create a note. Optional: category, content, favorite (plus 2 more). Returns the new NoteEntry."),
			mcplib.WithString("category", mcplib.Description("Category")),
			mcplib.WithString("content", mcplib.Description("Content")),
			mcplib.WithBoolean("favorite", mcplib.Description("Favorite")),
			mcplib.WithNumber("modified", mcplib.Description("Modified")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/index.php/apps/notes/api/v1/notes", false, []mcpParamBinding{{PublicName: "category", WireName: "category", Location: "body"}, {PublicName: "content", WireName: "content", Location: "body"}, {PublicName: "favorite", WireName: "favorite", Location: "body"}, {PublicName: "modified", WireName: "modified", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_delete-note",
			mcplib.WithDescription("Delete a note. Required: noteId. Destructive."),
			mcplib.WithNumber("noteId", mcplib.Required(), mcplib.Description("Note id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/index.php/apps/notes/api/v1/notes/{noteId}", false, []mcpParamBinding{{PublicName: "noteId", WireName: "noteId", Location: "path"}}, []string{"noteId"}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_get-deck-board",
			mcplib.WithDescription("Get a Deck board. Required: boardId. Returns the DeckBoard."),
			mcplib.WithNumber("boardId", mcplib.Required(), mcplib.Description("Board id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index.php/apps/deck/api/v1.0/boards/{boardId}", false, []mcpParamBinding{{PublicName: "boardId", WireName: "boardId", Location: "path"}}, []string{"boardId"}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_get-note",
			mcplib.WithDescription("Get a note. Required: noteId. Returns the NoteEntry."),
			mcplib.WithNumber("noteId", mcplib.Required(), mcplib.Description("Note id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index.php/apps/notes/api/v1/notes/{noteId}", false, []mcpParamBinding{{PublicName: "noteId", WireName: "noteId", Location: "path"}}, []string{"noteId"}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_list-deck-boards",
			mcplib.WithDescription("List Deck boards. Optional: details. Returns array of DeckBoard."),
			mcplib.WithNumber("details", mcplib.Description("Details")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index.php/apps/deck/api/v1.0/boards", false, []mcpParamBinding{{PublicName: "details", WireName: "details", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_list-deck-stacks",
			mcplib.WithDescription("List stacks in a Deck board. Required: boardId. Returns array of DeckStack."),
			mcplib.WithNumber("boardId", mcplib.Required(), mcplib.Description("Board id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index.php/apps/deck/api/v1.0/boards/{boardId}/stacks", false, []mcpParamBinding{{PublicName: "boardId", WireName: "boardId", Location: "path"}}, []string{"boardId"}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_list-notes",
			mcplib.WithDescription("List all notes. Optional: category, exclude, pagesizes (plus 1 more). Returns array of NoteEntry."),
			mcplib.WithString("category", mcplib.Description("Filter by category")),
			mcplib.WithString("exclude", mcplib.Description("Fields to exclude (comma-separated, e.g. 'content' for titles only)")),
			mcplib.WithNumber("pagesizes", mcplib.Description("Pagesizes")),
			mcplib.WithNumber("chunksize", mcplib.Description("Chunksize")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/index.php/apps/notes/api/v1/notes", false, []mcpParamBinding{{PublicName: "category", WireName: "category", Location: "query"}, {PublicName: "exclude", WireName: "exclude", Location: "query"}, {PublicName: "pagesizes", WireName: "pagesizes", Location: "query"}, {PublicName: "chunksize", WireName: "chunksize", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("index-php_update-note",
			mcplib.WithDescription("Update a note. Required: noteId. Optional: category, content, favorite (plus 1 more). Returns the updated NoteEntry."),
			mcplib.WithNumber("noteId", mcplib.Required(), mcplib.Description("Note id")),
			mcplib.WithString("category", mcplib.Description("Category")),
			mcplib.WithString("content", mcplib.Description("Content")),
			mcplib.WithBoolean("favorite", mcplib.Description("Favorite")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/index.php/apps/notes/api/v1/notes/{noteId}", false, []mcpParamBinding{{PublicName: "noteId", WireName: "noteId", Location: "path"}, {PublicName: "category", WireName: "category", Location: "body"}, {PublicName: "content", WireName: "content", Location: "body"}, {PublicName: "favorite", WireName: "favorite", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"noteId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_add-user-to-group",
			mcplib.WithDescription("Add user to group. Required: userId, groupid. Optional: format (default: json). Returns the new OcsAddUserToGroupResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithString("groupid", mcplib.Required(), mcplib.Description("Groupid")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/cloud/users/{userId}/groups", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "userId", WireName: "userId", Location: "path", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "groupid", WireName: "groupid", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_clear-user-status-message",
			mcplib.WithDescription("Clear user status message. Optional: format (default: json). Returns the OcsClearUserStatusMessageResponse. Destructive."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/ocs/v2.php/apps/user_status/api/v1/user_status/message", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_create-group",
			mcplib.WithDescription("Create a group. Required: groupid. Optional: format (default: json), displayname. Returns the new OcsCreateGroupResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("displayname", mcplib.Description("Displayname")),
			mcplib.WithString("groupid", mcplib.Required(), mcplib.Description("Groupid")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/cloud/groups", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "displayname", WireName: "displayname", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "groupid", WireName: "groupid", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_create-share",
			mcplib.WithDescription("Create a share. Required: path, shareType. Optional: format (default: json), expireDate, hideDownload (plus 5 more). Returns the new OcsCreateShareResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("expireDate", mcplib.Description("Expiry date (YYYY-MM-DD)")),
			mcplib.WithBoolean("hideDownload", mcplib.Description("Hide download")),
			mcplib.WithString("label", mcplib.Description("Label")),
			mcplib.WithString("note", mcplib.Description("Note")),
			mcplib.WithString("password", mcplib.Description("Password for public link")),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Path to the item to share")),
			mcplib.WithNumber("permissions", mcplib.Description("Permission bitmap: 1=read, 2=update, 4=create, 8=delete, 16=share, 31=all")),
			mcplib.WithNumber("shareType", mcplib.Required(), mcplib.Description("0=user, 1=group, 3=public link, 4=email, 6=federated, 7=circle, 10=talk")),
			mcplib.WithString("shareWith", mcplib.Description("User/group/email to share with (not required for public links)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/apps/files_sharing/api/v1/shares", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "expireDate", WireName: "expireDate", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "hideDownload", WireName: "hideDownload", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "label", WireName: "label", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "note", WireName: "note", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "password", WireName: "password", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "path", WireName: "path", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "permissions", WireName: "permissions", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "shareType", WireName: "shareType", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "shareWith", WireName: "shareWith", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_create-user",
			mcplib.WithDescription("Create a new user. Required: userid. Optional: format (default: json), displayName, email (plus 5 more). Returns the new OcsCreateUserResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("displayName", mcplib.Description("Display name")),
			mcplib.WithString("email", mcplib.Description("Email")),
			mcplib.WithString("groups", mcplib.Description("Groups")),
			mcplib.WithString("language", mcplib.Description("Language")),
			mcplib.WithString("password", mcplib.Description("Password")),
			mcplib.WithString("quota", mcplib.Description("Quota")),
			mcplib.WithString("subadmin", mcplib.Description("Subadmin")),
			mcplib.WithString("userid", mcplib.Required(), mcplib.Description("Userid")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/cloud/users", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "displayName", WireName: "displayName", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "email", WireName: "email", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "groups", WireName: "groups", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "language", WireName: "language", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "password", WireName: "password", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "quota", WireName: "quota", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "subadmin", WireName: "subadmin", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "userid", WireName: "userid", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_delete-group",
			mcplib.WithDescription("Delete a group. Required: groupId. Optional: format (default: json). Returns the OcsDeleteGroupResponse. Destructive."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("groupId", mcplib.Required(), mcplib.Description("Group id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/ocs/v2.php/cloud/groups/{groupId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "groupId", WireName: "groupId", Location: "path"}}, []string{"groupId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_delete-share",
			mcplib.WithDescription("Delete a share. Required: shareId. Optional: format (default: json). Returns the OcsDeleteShareResponse. Destructive."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("shareId", mcplib.Required(), mcplib.Description("Share id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/ocs/v2.php/apps/files_sharing/api/v1/shares/{shareId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "shareId", WireName: "shareId", Location: "path"}}, []string{"shareId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_delete-user",
			mcplib.WithDescription("Delete a user. Required: userId. Optional: format (default: json). Returns the OcsDeleteUserResponse. Destructive."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/ocs/v2.php/cloud/users/{userId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_disable-user",
			mcplib.WithDescription("Disable a user. Required: userId. Optional: format (default: json). Returns the updated OcsDisableUserResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/ocs/v2.php/cloud/users/{userId}/disable", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_enable-user",
			mcplib.WithDescription("Enable a user. Required: userId. Optional: format (default: json). Returns the updated OcsEnableUserResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/ocs/v2.php/cloud/users/{userId}/enable", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-capabilities",
			mcplib.WithDescription("Get server capabilities and version. Optional: format (default: json). Returns the OcsGetCapabilitiesResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/capabilities", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-group-members",
			mcplib.WithDescription("Get group members. Required: groupId. Optional: format (default: json). Returns the OcsGetGroupMembersResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("groupId", mcplib.Required(), mcplib.Description("Group id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/groups/{groupId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "groupId", WireName: "groupId", Location: "path"}}, []string{"groupId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-share",
			mcplib.WithDescription("Get share details. Required: shareId. Optional: format (default: json). Returns the OcsGetShareResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("shareId", mcplib.Required(), mcplib.Description("Share id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/files_sharing/api/v1/shares/{shareId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "shareId", WireName: "shareId", Location: "path"}}, []string{"shareId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-user",
			mcplib.WithDescription("Get user details. Required: userId. Optional: format (default: json). Returns the OcsGetUserResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/users/{userId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-user-groups",
			mcplib.WithDescription("Get groups for a user. Required: userId. Optional: format (default: json). Returns the OcsGetUserGroupsResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/users/{userId}/groups", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_get-user-status",
			mcplib.WithDescription("Get own user status. Optional: format (default: json). Returns the OcsGetUserStatusResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/user_status/api/v1/user_status", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-activity",
			mcplib.WithDescription("List activity feed. Optional: format (default: json), filter, limit (default: 50) (plus 5 more). Returns the OcsListActivityResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("filter", mcplib.Description("Activity type filter (e.g. files, shared, contacts)")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("since", mcplib.Description("Activity ID to start from (pagination)")),
			mcplib.WithNumber("until", mcplib.Description("Until")),
			mcplib.WithString("sort", mcplib.Description("Sort")),
			mcplib.WithString("object_type", mcplib.Description("Object type")),
			mcplib.WithNumber("object_id", mcplib.Description("Object id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/activity/api/v2/activity/filter", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "filter", WireName: "filter", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "since", WireName: "since", Location: "query"}, {PublicName: "until", WireName: "until", Location: "query"}, {PublicName: "sort", WireName: "sort", Location: "query"}, {PublicName: "object_type", WireName: "object_type", Location: "query"}, {PublicName: "object_id", WireName: "object_id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-groups",
			mcplib.WithDescription("List groups. Optional: format (default: json), search, limit (default: 100) (plus 1 more). Returns the OcsListGroupsResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("search", mcplib.Description("Search")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("offset", mcplib.Description("Offset")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/groups", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "search", WireName: "search", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-notifications",
			mcplib.WithDescription("List your notifications. Optional: format (default: json). Returns the OcsListNotificationsResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/notifications/api/v2/notifications", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-rooms",
			mcplib.WithDescription("List Talk conversations. Optional: format (default: json), noStatusUpdate, includeStatus. Returns the OcsListRoomsResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("noStatusUpdate", mcplib.Description("No status update")),
			mcplib.WithBoolean("includeStatus", mcplib.Description("Include status")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/spreed/api/v4/room", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "noStatusUpdate", WireName: "noStatusUpdate", Location: "query"}, {PublicName: "includeStatus", WireName: "includeStatus", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-shares",
			mcplib.WithDescription("List all shares. Optional: format (default: json), path, reshares (plus 2 more). Returns the OcsListSharesResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("path", mcplib.Description("Filter shares for a specific path")),
			mcplib.WithBoolean("reshares", mcplib.Description("Reshares")),
			mcplib.WithBoolean("subfiles", mcplib.Description("Also list shares of sub-files when path is a folder")),
			mcplib.WithBoolean("shared_with_me", mcplib.Description("Shared with me")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/files_sharing/api/v1/shares", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "path", WireName: "path", Location: "query"}, {PublicName: "reshares", WireName: "reshares", Location: "query"}, {PublicName: "subfiles", WireName: "subfiles", Location: "query"}, {PublicName: "shared_with_me", WireName: "shared_with_me", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-user-statuses",
			mcplib.WithDescription("List all user statuses. Optional: format (default: json), limit (default: 100), offset (default: 0). Returns the OcsListUserStatusesResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("offset", mcplib.Description("Offset")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/user_status/api/v1/statuses", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_list-users",
			mcplib.WithDescription("List users. Optional: format (default: json), search, limit (default: 100) (plus 2 more). Returns the OcsListUsersResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("search", mcplib.Description("Search filter")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("offset", mcplib.Description("Offset")),
			mcplib.WithBoolean("disabled", mcplib.Description("Only return disabled users")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/cloud/users", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "search", WireName: "search", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "offset", WireName: "offset", Location: "query"}, {PublicName: "disabled", WireName: "disabled", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_read-messages",
			mcplib.WithDescription("Read messages from a Talk room. Required: token. Optional: format (default: json), lookIntoFuture (default: 0), limit (default: 100) (plus 5 more). Returns the OcsReadMessagesResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("token", mcplib.Required(), mcplib.Description("Room token")),
			mcplib.WithNumber("lookIntoFuture", mcplib.Description("Look into future")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithNumber("lastKnownMessageId", mcplib.Description("Last known message id")),
			mcplib.WithNumber("lastCommonReadMessageId", mcplib.Description("Last common read message id")),
			mcplib.WithNumber("timeout", mcplib.Description("Timeout")),
			mcplib.WithNumber("setReadMarker", mcplib.Description("Set read marker")),
			mcplib.WithNumber("includeLastKnown", mcplib.Description("Include last known")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/ocs/v2.php/apps/spreed/api/v1/chat/{token}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "token", WireName: "token", Location: "path"}, {PublicName: "lookIntoFuture", WireName: "lookIntoFuture", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query"}, {PublicName: "lastKnownMessageId", WireName: "lastKnownMessageId", Location: "query"}, {PublicName: "lastCommonReadMessageId", WireName: "lastCommonReadMessageId", Location: "query"}, {PublicName: "timeout", WireName: "timeout", Location: "query"}, {PublicName: "setReadMarker", WireName: "setReadMarker", Location: "query"}, {PublicName: "includeLastKnown", WireName: "includeLastKnown", Location: "query"}}, []string{"token"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_remove-user-from-group",
			mcplib.WithDescription("Remove user from group. Required: userId, groupId. Optional: format (default: json). Returns the OcsRemoveUserFromGroupResponse. Destructive."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithString("groupId", mcplib.Required(), mcplib.Description("Group id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/ocs/v2.php/cloud/users/{userId}/groups/{groupId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query"}, {PublicName: "userId", WireName: "userId", Location: "path"}, {PublicName: "groupId", WireName: "groupId", Location: "path"}}, []string{"userId", "groupId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_send-message",
			mcplib.WithDescription("Send a message to a Talk room. Required: token, message. Optional: format (default: json), actorDisplayName, referenceId (plus 1 more). Returns the new OcsSendMessageResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("token", mcplib.Required(), mcplib.Description("Token")),
			mcplib.WithString("actorDisplayName", mcplib.Description("Actor display name")),
			mcplib.WithString("message", mcplib.Required(), mcplib.Description("Message")),
			mcplib.WithString("referenceId", mcplib.Description("Reference id")),
			mcplib.WithNumber("replyTo", mcplib.Description("Reply to")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/apps/spreed/api/v1/chat/{token}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "token", WireName: "token", Location: "path", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "actorDisplayName", WireName: "actorDisplayName", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "message", WireName: "message", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "referenceId", WireName: "referenceId", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "replyTo", WireName: "replyTo", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{"token"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_send-notification",
			mcplib.WithDescription("Send a notification to a user. Required: userId, shortMessage. Optional: format (default: json), longMessage. Returns the new OcsSendNotificationResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithString("longMessage", mcplib.Description("Long message")),
			mcplib.WithString("shortMessage", mcplib.Required(), mcplib.Description("Short message")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/ocs/v2.php/apps/admin_notifications/api/v1/notifications/{userId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "userId", WireName: "userId", Location: "path", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "longMessage", WireName: "longMessage", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "shortMessage", WireName: "shortMessage", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_set-user-status-message",
			mcplib.WithDescription("Set user status message. Optional: format (default: json), clearAt, message (plus 1 more). Returns the updated OcsSetUserStatusMessageResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithNumber("clearAt", mcplib.Description("Clear at")),
			mcplib.WithString("message", mcplib.Description("Message")),
			mcplib.WithString("statusIcon", mcplib.Description("Status icon")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/ocs/v2.php/apps/user_status/api/v1/user_status/message/custom", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "clearAt", WireName: "clearAt", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "message", WireName: "message", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "statusIcon", WireName: "statusIcon", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_update-share",
			mcplib.WithDescription("Update a share (permissions, expiry, password). Required: shareId. Optional: format (default: json), expireDate, hideDownload (plus 3 more). Returns the updated OcsUpdateShareResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("shareId", mcplib.Required(), mcplib.Description("Share id")),
			mcplib.WithString("expireDate", mcplib.Description("Expire date")),
			mcplib.WithBoolean("hideDownload", mcplib.Description("Hide download")),
			mcplib.WithString("note", mcplib.Description("Note")),
			mcplib.WithString("password", mcplib.Description("Password")),
			mcplib.WithNumber("permissions", mcplib.Description("Permissions")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/ocs/v2.php/apps/files_sharing/api/v1/shares/{shareId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "shareId", WireName: "shareId", Location: "path", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "expireDate", WireName: "expireDate", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "hideDownload", WireName: "hideDownload", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "note", WireName: "note", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "password", WireName: "password", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "permissions", WireName: "permissions", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{"shareId"}),
	)
	s.AddTool(
		mcplib.NewTool("ocs_update-user",
			mcplib.WithDescription("Update user attributes. Required: userId. Optional: format (default: json), key, value. Returns the updated OcsUpdateUserResponse."),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithString("userId", mcplib.Required(), mcplib.Description("User id")),
			mcplib.WithString("key", mcplib.Description("Key")),
			mcplib.WithString("value", mcplib.Description("Value")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/ocs/v2.php/cloud/users/{userId}", false, []mcpParamBinding{{PublicName: "format", WireName: "format", Location: "query", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "userId", WireName: "userId", Location: "path", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "key", WireName: "key", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}, {PublicName: "value", WireName: "value", Location: "body", RequestContentType: "application/x-www-form-urlencoded"}}, []string{"userId"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_create-contact",
			mcplib.WithDescription("Create/update a contact (CardDAV PUT). Required: user, addressbook (default: contacts), contactFile."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("addressbook", mcplib.Required(), mcplib.Description("Addressbook")),
			mcplib.WithString("contactFile", mcplib.Required(), mcplib.Description("Filename for the contact (e.g. contact-uid.vcf)")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/remote.php/dav/addressbooks/{user}/{addressbook}/{contactFile}", false, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "addressbook", WireName: "addressbook", Location: "path"}, {PublicName: "contactFile", WireName: "contactFile", Location: "path"}}, []string{"user", "addressbook", "contactFile"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_create-event",
			mcplib.WithDescription("Create a calendar event (CalDAV PUT). Required: user, calendar, eventFile."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("calendar", mcplib.Required(), mcplib.Description("Calendar")),
			mcplib.WithString("eventFile", mcplib.Required(), mcplib.Description("Filename for the event (e.g. event-uid.ics)")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/remote.php/dav/calendars/{user}/{calendar}/{eventFile}", false, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "calendar", WireName: "calendar", Location: "path"}, {PublicName: "eventFile", WireName: "eventFile", Location: "path"}}, []string{"user", "calendar", "eventFile"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_create-system-tag",
			mcplib.WithDescription("Create a system tag. Required: name. Optional: userAssignable (default: true), userVisible (default: true)."),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithBoolean("userAssignable", mcplib.Description("User assignable")),
			mcplib.WithBoolean("userVisible", mcplib.Description("User visible")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/remote.php/dav/systemtags", false, []mcpParamBinding{{PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "userAssignable", WireName: "userAssignable", Location: "body"}, {PublicName: "userVisible", WireName: "userVisible", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_delete-contact",
			mcplib.WithDescription("Delete a contact. Required: user, addressbook, contactFile. Destructive."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("addressbook", mcplib.Required(), mcplib.Description("Addressbook")),
			mcplib.WithString("contactFile", mcplib.Required(), mcplib.Description("Contact file")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/remote.php/dav/addressbooks/{user}/{addressbook}/{contactFile}", false, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "addressbook", WireName: "addressbook", Location: "path"}, {PublicName: "contactFile", WireName: "contactFile", Location: "path"}}, []string{"user", "addressbook", "contactFile"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_delete-file",
			mcplib.WithDescription("Delete a file or directory. Required: user, path. Destructive."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Path")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/remote.php/dav/files/{user}/{path}", false, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "path", WireName: "path", Location: "path"}}, []string{"user", "path"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_download-file",
			mcplib.WithDescription("Download a file. Required: user, path."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Remote path to file (e.g. Documents/report.pdf)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/remote.php/dav/files/{user}/{path}", true, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "path", WireName: "path", Location: "path"}}, []string{"user", "path"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_tag-file",
			mcplib.WithDescription("Tag a file with a system tag. Required: fileId, tagId."),
			mcplib.WithNumber("fileId", mcplib.Required(), mcplib.Description("File id")),
			mcplib.WithNumber("tagId", mcplib.Required(), mcplib.Description("Tag id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/remote.php/dav/systemtags-relations/files/{fileId}/{tagId}", false, []mcpParamBinding{{PublicName: "fileId", WireName: "fileId", Location: "path"}, {PublicName: "tagId", WireName: "tagId", Location: "path"}}, []string{"fileId", "tagId"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_untag-file",
			mcplib.WithDescription("Remove a tag from a file. Required: fileId, tagId. Destructive."),
			mcplib.WithNumber("fileId", mcplib.Required(), mcplib.Description("File id")),
			mcplib.WithNumber("tagId", mcplib.Required(), mcplib.Description("Tag id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/remote.php/dav/systemtags-relations/files/{fileId}/{tagId}", false, []mcpParamBinding{{PublicName: "fileId", WireName: "fileId", Location: "path"}, {PublicName: "tagId", WireName: "tagId", Location: "path"}}, []string{"fileId", "tagId"}),
	)
	s.AddTool(
		mcplib.NewTool("remote-php_upload-file",
			mcplib.WithDescription("Upload a file. Required: user, path."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Remote destination path")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/remote.php/dav/files/{user}/{path}", false, []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "path"}, {PublicName: "path", WireName: "path", Location: "path"}}, []string{"user", "path"}),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName         string
	WireName           string
	Location           string
	Format             string
	RequestContentType string
}

func mcpFormFieldValue(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	if data, err := json.Marshal(v); err == nil {
		return string(data)
	}
	return fmt.Sprintf("%v", v)
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		formFields := url.Values{}
		formEncoded := false
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			if strings.EqualFold(binding.RequestContentType, "application/x-www-form-urlencoded") {
				formEncoded = true
			}
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
				if formEncoded {
					formFields.Set(binding.WireName, mcpFormFieldValue(v))
				}
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
				if formEncoded {
					formFields.Set(k, mcpFormFieldValue(v))
				}
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if formEncoded {
				if binaryResponse {
					data, _, err = c.PostFormWithParamsAndHeaders(path, params, formFields, headers)
					break
				}
				data, _, err = c.PostFormWithParams(path, params, formFields)
				break
			}
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if formEncoded {
				if binaryResponse {
					data, _, err = c.PutFormWithParamsAndHeaders(path, params, formFields, headers)
					break
				}
				data, _, err = c.PutFormWithParams(path, params, formFields)
				break
			}
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if formEncoded {
				if binaryResponse {
					data, _, err = c.PatchFormWithParamsAndHeaders(path, params, formFields, headers)
					break
				}
				data, _, err = c.PatchFormWithParams(path, params, formFields)
				break
			}
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export NEXTCLOUD_USERNAME=<your-key>" +
					"\n      Run 'nextcloud-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export NEXTCLOUD_USERNAME=<your-key>" +
					"\n      Run 'nextcloud-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export NEXTCLOUD_USERNAME=<your-key>" +
					"\n      Run 'nextcloud-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "nextcloud-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "nextcloud-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "nextcloud",
		"description": "Nextcloud OCS v2, WebDAV, CalDAV, CardDAV, and app APIs for files, sharing, users, notes, calendar, Talk, activity,...",
		"archetype":   "generic",
		"tool_count":  49,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion nextcloud-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":      "NEXTCLOUD_USERNAME",
					"kind":      "per_call",
					"required":  true,
					"sensitive": false,
				},
				{
					"name":        "NEXTCLOUD_PASSWORD",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "index-php",
				"description": "Manage index php",
				"endpoints":   []string{"create-deck-board", "create-deck-card", "create-note", "delete-note", "get-deck-board", "get-note", "list-deck-boards", "list-deck-stacks", "list-notes", "update-note"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "ocs",
				"description": "Manage ocs",
				"endpoints":   []string{"add-user-to-group", "clear-user-status-message", "create-group", "create-share", "create-user", "delete-group", "delete-share", "delete-user", "disable-user", "enable-user", "get-capabilities", "get-group-members", "get-share", "get-user", "get-user-groups", "get-user-status", "list-activity", "list-groups", "list-notifications", "list-rooms", "list-shares", "list-user-statuses", "list-users", "read-messages", "remove-user-from-group", "send-message", "send-notification", "set-user-status-message", "update-share", "update-user"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "remote-php",
				"description": "Manage remote php",
				"endpoints":   []string{"create-contact", "create-event", "create-system-tag", "delete-contact", "delete-file", "download-file", "tag-file", "untag-file", "upload-file"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass offset parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use since for incremental fetches (filter by modification time).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
