// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIndexPhpCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "index-php",
		Short: "Manage index php",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIndexPhpCreateDeckBoardCmd(flags))
	cmd.AddCommand(newIndexPhpCreateDeckCardCmd(flags))
	cmd.AddCommand(newIndexPhpCreateNoteCmd(flags))
	cmd.AddCommand(newIndexPhpDeleteNoteCmd(flags))
	cmd.AddCommand(newIndexPhpGetDeckBoardCmd(flags))
	cmd.AddCommand(newIndexPhpGetNoteCmd(flags))
	cmd.AddCommand(newIndexPhpListDeckBoardsCmd(flags))
	cmd.AddCommand(newIndexPhpListDeckStacksCmd(flags))
	cmd.AddCommand(newIndexPhpListNotesCmd(flags))
	cmd.AddCommand(newIndexPhpUpdateNoteCmd(flags))
	return cmd
}
