// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newIndexPhpListNotesCmd(flags *rootFlags) *cobra.Command {
	var flagCategory string
	var flagExclude string
	var flagPagesizes int
	var flagChunksize int

	cmd := &cobra.Command{
		Use:         "list-notes",
		Short:       "List all notes",
		Example:     "  nextcloud-pp-cli index-php list-notes",
		Annotations: map[string]string{"pp:endpoint": "index-php.list-notes", "pp:method": "GET", "pp:path": "/index.php/apps/notes/api/v1/notes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/index.php/apps/notes/api/v1/notes"
			params := map[string]string{}
			if flagCategory != "" {
				params["category"] = fmt.Sprintf("%v", flagCategory)
			}
			if flagExclude != "" {
				params["exclude"] = fmt.Sprintf("%v", flagExclude)
			}
			if flagPagesizes != 0 {
				params["pagesizes"] = fmt.Sprintf("%v", flagPagesizes)
			}
			if flagChunksize != 0 {
				params["chunksize"] = fmt.Sprintf("%v", flagChunksize)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "index-php", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCategory, "category", "", "Filter by category")
	cmd.Flags().StringVar(&flagExclude, "exclude", "", "Fields to exclude (comma-separated, e.g. 'content' for titles only)")
	cmd.Flags().IntVar(&flagPagesizes, "pagesizes", 0, "Pagesizes")
	cmd.Flags().IntVar(&flagChunksize, "chunksize", 0, "Chunksize")

	return cmd
}
