// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOcsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ocs",
		Short: "Manage ocs",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOcsAddUserToGroupCmd(flags))
	cmd.AddCommand(newOcsClearUserStatusMessageCmd(flags))
	cmd.AddCommand(newOcsCreateGroupCmd(flags))
	cmd.AddCommand(newOcsCreateShareCmd(flags))
	cmd.AddCommand(newOcsCreateUserCmd(flags))
	cmd.AddCommand(newOcsDeleteGroupCmd(flags))
	cmd.AddCommand(newOcsDeleteShareCmd(flags))
	cmd.AddCommand(newOcsDeleteUserCmd(flags))
	cmd.AddCommand(newOcsDisableUserCmd(flags))
	cmd.AddCommand(newOcsEnableUserCmd(flags))
	cmd.AddCommand(newOcsGetCapabilitiesCmd(flags))
	cmd.AddCommand(newOcsGetGroupMembersCmd(flags))
	cmd.AddCommand(newOcsGetShareCmd(flags))
	cmd.AddCommand(newOcsGetUserCmd(flags))
	cmd.AddCommand(newOcsGetUserGroupsCmd(flags))
	cmd.AddCommand(newOcsGetUserStatusCmd(flags))
	cmd.AddCommand(newOcsListActivityCmd(flags))
	cmd.AddCommand(newOcsListGroupsCmd(flags))
	cmd.AddCommand(newOcsListNotificationsCmd(flags))
	cmd.AddCommand(newOcsListRoomsCmd(flags))
	cmd.AddCommand(newOcsListSharesCmd(flags))
	cmd.AddCommand(newOcsListUserStatusesCmd(flags))
	cmd.AddCommand(newOcsListUsersCmd(flags))
	cmd.AddCommand(newOcsReadMessagesCmd(flags))
	cmd.AddCommand(newOcsRemoveUserFromGroupCmd(flags))
	cmd.AddCommand(newOcsSendMessageCmd(flags))
	cmd.AddCommand(newOcsSendNotificationCmd(flags))
	cmd.AddCommand(newOcsSetUserStatusMessageCmd(flags))
	cmd.AddCommand(newOcsUpdateShareCmd(flags))
	cmd.AddCommand(newOcsUpdateUserCmd(flags))
	return cmd
}
