// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"

	"github.com/spf13/cobra"
)

func newOcsCreateShareCmd(flags *rootFlags) *cobra.Command {
	var flagFormat string
	var bodyExpireDate string
	var bodyHideDownload bool
	var bodyLabel string
	var bodyNote string
	var bodyPassword string
	var bodyPath string
	var bodyPermissions int
	var bodyShareType int
	var bodyShareWith string

	cmd := &cobra.Command{
		Use:         "create-share",
		Short:       "Create a share",
		Example:     "  nextcloud-pp-cli ocs create-share --path example-value",
		Annotations: map[string]string{"pp:endpoint": "ocs.create-share", "pp:method": "POST", "pp:path": "/ocs/v2.php/apps/files_sharing/api/v1/shares"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("path") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "path")
			}
			if !cmd.Flags().Changed("share-type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "share-type")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ocs/v2.php/apps/files_sharing/api/v1/shares"
			params := map[string]string{}
			if flagFormat != "" {
				params["format"] = fmt.Sprintf("%v", flagFormat)
			}
			fields := url.Values{}
			if bodyExpireDate != "" {
				fields.Set("expireDate", bodyExpireDate)
			}
			if bodyHideDownload != false {
				fields.Set("hideDownload", fmt.Sprintf("%v", bodyHideDownload))
			}
			if bodyLabel != "" {
				fields.Set("label", bodyLabel)
			}
			if bodyNote != "" {
				fields.Set("note", bodyNote)
			}
			if bodyPassword != "" {
				fields.Set("password", bodyPassword)
			}
			if bodyPath != "" {
				fields.Set("path", bodyPath)
			}
			if bodyPermissions != 0 {
				fields.Set("permissions", fmt.Sprintf("%v", bodyPermissions))
			}
			if bodyShareType != 0 {
				fields.Set("shareType", fmt.Sprintf("%v", bodyShareType))
			}
			if bodyShareWith != "" {
				fields.Set("shareWith", bodyShareWith)
			}

			data, statusCode, err := c.PostFormWithParams(path, params, fields)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "ocs", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ocs", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ocs", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ocs", partialFailure.Message))
					}
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "ocs",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ocs", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "ocs", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&flagFormat, "format", "json", "Format")
	cmd.Flags().StringVar(&bodyExpireDate, "expire-date", "", "Expiry date (YYYY-MM-DD)")
	cmd.Flags().BoolVar(&bodyHideDownload, "hide-download", false, "Hide download")
	cmd.Flags().StringVar(&bodyLabel, "label", "", "Label")
	cmd.Flags().StringVar(&bodyNote, "note", "", "Note")
	cmd.Flags().StringVar(&bodyPassword, "password", "", "Password for public link")
	cmd.Flags().StringVar(&bodyPath, "path", "", "Path to the item to share")
	cmd.Flags().IntVar(&bodyPermissions, "permissions", 0, "Permission bitmap: 1=read, 2=update, 4=create, 8=delete, 16=share, 31=all")
	cmd.Flags().IntVar(&bodyShareType, "share-type", 0, "0=user, 1=group, 3=public link, 4=email, 6=federated, 7=circle, 10=talk")
	cmd.Flags().StringVar(&bodyShareWith, "share-with", "", "User/group/email to share with (not required for public links)")

	return cmd
}
