// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOcsListActivityCmd(flags *rootFlags) *cobra.Command {
	var flagFormat string
	var flagFilter string
	var flagLimit int
	var flagSince int
	var flagUntil int
	var flagSort string
	var flagObjectType string
	var flagObjectId string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-activity",
		Short:       "List activity feed",
		Example:     "  nextcloud-pp-cli ocs list-activity",
		Annotations: map[string]string{"pp:endpoint": "ocs.list-activity", "pp:method": "GET", "pp:path": "/ocs/v2.php/apps/activity/api/v2/activity/filter", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"asc", "desc"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ocs/v2.php/apps/activity/api/v2/activity/filter"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "ocs", path, map[string]string{
				"format":      fmt.Sprintf("%v", flagFormat),
				"filter":      fmt.Sprintf("%v", flagFilter),
				"limit":       fmt.Sprintf("%v", flagLimit),
				"since":       fmt.Sprintf("%v", flagSince),
				"until":       fmt.Sprintf("%v", flagUntil),
				"sort":        fmt.Sprintf("%v", flagSort),
				"object_type": fmt.Sprintf("%v", flagObjectType),
				"object_id":   fmt.Sprintf("%v", flagObjectId),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFormat, "format", "json", "Format")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "Activity type filter (e.g. files, shared, contacts)")
	cmd.Flags().IntVar(&flagLimit, "limit", 50, "Limit")
	cmd.Flags().IntVar(&flagSince, "since", 0, "Activity ID to start from (pagination)")
	cmd.Flags().IntVar(&flagUntil, "until", 0, "Until")
	cmd.Flags().StringVar(&flagSort, "sort", "desc", "Sort (one of: asc, desc)")
	cmd.Flags().StringVar(&flagObjectType, "object-type", "", "Object type")
	cmd.Flags().StringVar(&flagObjectId, "object-id", "", "Object id")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
