// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRemotePhpCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "remote-php",
		Short: "Manage remote php",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRemotePhpCreateContactCmd(flags))
	cmd.AddCommand(newRemotePhpCreateEventCmd(flags))
	cmd.AddCommand(newRemotePhpCreateSystemTagCmd(flags))
	cmd.AddCommand(newRemotePhpDeleteContactCmd(flags))
	cmd.AddCommand(newRemotePhpDeleteFileCmd(flags))
	cmd.AddCommand(newRemotePhpDownloadFileCmd(flags))
	cmd.AddCommand(newRemotePhpTagFileCmd(flags))
	cmd.AddCommand(newRemotePhpUntagFileCmd(flags))
	cmd.AddCommand(newRemotePhpUploadFileCmd(flags))
	cmd.AddCommand(newRemotePhpListFilesCmd(flags))
	cmd.AddCommand(newRemotePhpMkdirCmd(flags))
	cmd.AddCommand(newRemotePhpMoveCmd(flags))
	cmd.AddCommand(newRemotePhpCopyCmd(flags))
	return cmd
}
