// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newRemotePhpDownloadFileCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "download-file <user> <path>",
		Aliases:     []string{"get"},
		Short:       "Download a file",
		Example:     "  nextcloud-pp-cli remote-php download-file example-value example-value",
		Annotations: map[string]string{"pp:endpoint": "remote-php.download-file", "pp:method": "GET", "pp:path": "/remote.php/dav/files/{user}/{path}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/remote.php/dav/files/{user}/{path}"
			path = replacePathParam(path, "user", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("path is required\nUsage: %s <%s>", cmd.CommandPath(), "path"))
			}
			path = replacePathParam(path, "path", args[1])
			headerOverrides := map[string]string{
				"X-Printing-Press-Binary-Response": "true",
			}
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "remote-php", false, path, params, headerOverrides)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			_ = json.Valid
			_ = os.Stderr
			_ = prov
			if flags.quiet {
				return nil
			}
			if flags.asJSON || flags.csv || flags.compact || flags.plain || flags.selectFields != "" {
				return fmt.Errorf("binary response cannot be rendered as structured output; redirect stdout or use --deliver file:<path>")
			}
			_, err = cmd.OutOrStdout().Write(data)
			return err
		},
	}

	return cmd
}
