// Copyright 2026 kelvincushman. Licensed under Apache-2.0. See LICENSE.
//
// Thin entrypoint that delegates to internal/cli. The Cobra command tree
// (root + every subcommand) is generated by CLI Printing Press into
// internal/cli/; cli.Execute() wires the root command and runs it against
// os.Args.
package main

import (
	"os"

	"nextcloud-pp-cli/internal/cli"
)

func main() {
	if err := cli.Execute(); err != nil {
		os.Exit(1)
	}
}
